language: php
dist: trusty

branches:
  only:
    - master
    - trunk
    - /^release\/\d+\.\d+(\.\d+)?(-\S*)?$/
    - /^feature\/*/
    - /^hotfix\/\d+\.\d+(\.\d+)?(-\S*)?$/
    # Also build tags like 1.1.1 or 1.1 for deployment.
    - /^\d+\.\d+(\.\d+)?(-\S*)?$/

jobs:
  fast_finish: true
  include:
    - php: 7.3
      env: WP_VERSION=5.4 WP_MULTISITE=1 PHPUNIT=1 PHPCS=1 SECURITY=1
    - php: 5.6
      env: WP_VERSION=5.3 PHPLINT=1 PHPUNIT=1
    - php: 7.4
      env: WP_VERSION=5.4 PHPLINT=1 PHPUNIT=1
    - php: 7.0
      env: WP_VERSION=master WP_MULTISITE=1 PHPUNIT=1
    - php: "nightly"
      env: PHPLINT=1
    - stage: deploy
      env: WP_VERSION=5.3
      if: tag IS present
      before_install:
        - openssl aes-256-cbc -K $encrypted_2b922af4d08d_key -iv $encrypted_2b922af4d08d_iv -in ./deploy_keys/wpseo_woo_deploy.enc -out ./deploy_keys/wpseo_woo_deploy -d
        - chmod 600 ./deploy_keys/wpseo_woo_deploy
        - eval $(ssh-agent -s)
        - ssh-add ./deploy_keys/wpseo_woo_deploy
      before_deploy:
        - nvm install node
        - curl -o- -L https://yarnpkg.com/install.sh | bash
        - export PATH=$HOME/.yarn/bin:$PATH
        - yarn global add grunt-cli
        - yarn install
        - grunt set-version -new-version=$TRAVIS_TAG
        - grunt update-version
        - grunt artifact

      # If the commit was tagged, create an artifact and push it to the distribution github
      deploy:
        skip_cleanup: true
        provider: script
        script: bash scripts/deploy_to_dist.sh $TRAVIS_TAG wpseo-woocommerce
        on:
          tags: true
          repo: $TRAVIS_REPO_SLUG
          all_branches: true
  allow_failures:
    # Allow failures for unstable builds.
    - php: "nightly"
    - php: 7.0
      env: WP_VERSION=master WP_MULTISITE=1 PHPUNIT=1

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_install:
- phpenv config-rm xdebug.ini || echo 'No xdebug config.'
- export SECURITYCHECK_DIR=/tmp/security-checker

install:
- |
  if [[ "$PHPCS" == "1" || "$PHPUNIT" == "1" ]]; then
    composer install --no-interaction
  elif [[ "$TRAVIS_BUILD_STAGE_NAME" == "deploy" ]]; then
    composer install --no-dev --no-interaction
  fi

- if [[ "$SECURITY" == "1" ]]; then wget -P $SECURITYCHECK_DIR https://get.sensiolabs.org/security-checker.phar && chmod +x $SECURITYCHECK_DIR/security-checker.phar;fi

before_script:
- PLUGIN_SLUG=$(basename $(pwd))
- export WP_DEVELOP_DIR=/tmp/wordpress/
- export -f travis_fold
- export -f travis_time_start
- export -f travis_time_finish

# Clone WordPress
- |
  if [[ "$PHPUNIT" == "1" ]]; then
    git clone --depth=1 --branch="$WP_VERSION" git://develop.git.wordpress.org/ /tmp/wordpress
  fi

# Clone WPSEO and its submodule
- |
  if [[ "$PHPUNIT" == "1" ]]; then
    git clone --depth=1 --branch="trunk" https://github.com/Yoast-dist/wordpress-seo.git $WP_DEVELOP_DIR/src/wp-content/plugins/wordpress-seo
    cd /tmp/wordpress/src/wp-content/plugins/wordpress-seo
    composer install --no-dev --no-scripts --no-interaction --ignore-platform-reqs
    cd -
  fi

# Copy woocommerce seo to the test directory
- |
  if [[ "$PHPUNIT" == "1" ]]; then
    cd ..
    cp -r "$PLUGIN_SLUG" "/tmp/wordpress/src/wp-content/plugins/$PLUGIN_SLUG"
    cd /tmp/wordpress/
    cp wp-tests-config-sample.php wp-tests-config.php
    sed -i "s/youremptytestdbnamehere/wordpress_tests/" wp-tests-config.php
    sed -i "s/yourusernamehere/travis/" wp-tests-config.php
    sed -i "s/yourpasswordhere//" wp-tests-config.php
    mysql -e "CREATE DATABASE wordpress_tests;" -uroot
    cd "/tmp/wordpress/src/wp-content/plugins/$PLUGIN_SLUG"
    phpenv rehash
  fi

script:
# PHP Linting
- |
  if [[ "$PHPLINT" == "1" ]]; then
    travis_fold start "PHP.check" && travis_time_start
    find -L . -path ./vendor -prune -o -path ./node_modules -prune -o -name '*.php' -print0 | xargs -0 -n 1 -P 4 php -l
    travis_time_finish && travis_fold end "PHP.check"
  fi
# PHP CS
- |
  if [[ "$PHPCS" == "1" ]]; then
    travis_fold start "PHP.code-style" && travis_time_start
    composer check-cs
    travis_time_finish && travis_fold end "PHP.code-style"
  fi
# PHP Tests
- |
  if [[ "$PHPUNIT" == "1" ]]; then
    travis_fold start "PHP.tests" && travis_time_start
    composer integration-test
    travis_time_finish && travis_fold end "PHP.tests"
  fi
- |
  if [[ "$PHPUNIT" == "1"  ]]; then
    travis_fold start "PHP.tests" && travis_time_start
    composer test
    travis_time_finish && travis_fold end "PHP.tests"
  fi
- if [[ $TRAVIS_PHP_VERSION == "7.3" ]]; then composer validate --no-check-all; fi

# Check for known security vulnerabilities in the currently locked-in dependencies.
- if [[ "$SECURITY" == "1" ]]; then php $SECURITYCHECK_DIR/security-checker.phar -n security:check $(pwd)/composer.lock;fi
